documentation:
  - changed-files:
      - any-glob-to-any-file: ['**/*.md', 'docs/**/*']
ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**/*', 'Makefile']
dependencies:
  - changed-files:
      - any-glob-to-any-file: ['go.mod', 'go.sum', 'Dockerfile', '.devcontainer/**/*']
tests:
  - changed-files:
      - any-glob-to-any-file: ['**/*_test.go', 'testdata/**/*']
