name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the following information to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add logs to help explain the problem.
      placeholder: Paste relevant logs here...
      render: shell

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of GopherPass are you using?
      placeholder: e.g., v1.0.13
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running GopherPass?
      options:
        - Docker
        - Binary
        - Build from source
        - Other
    validations:
      required: true

  - type: input
    id: ldap-server
    attributes:
      label: LDAP Server Type
      description: What LDAP server are you using?
      placeholder: e.g., Active Directory, OpenLDAP, FreeIPA

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Relevant environment information
      placeholder: |
        - OS: [e.g., Ubuntu 24.04]
        - Browser: [e.g., Chrome 120]
        - Go version (if building from source): [e.g., 1.25]
      value: |
        - OS:
        - Browser:
        - Go version:

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information...

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues and this is not a duplicate
          required: true
        - label: I have redacted any sensitive information from logs and screenshots
          required: true
        - label: I am using the latest version (or have checked the changelog)
          required: false
