name: Container

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  container:
    uses: netresearch/.github/.github/workflows/build-container.yml@main
    with:
      image-name: ${{ github.repository }}
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
      security-events: write
