name: Gitleaks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  gitleaks:
    uses: netresearch/.github/.github/workflows/gitleaks.yml@main
    permissions:
      contents: read
